### PR TITLE
drop python2 support

### PR DESCRIPTION
**Pull request by a-detiste**
keep your project alive

### CODE REVIEW

**Comment by halfak** [comment]
When I run pytest, I get a couple of errors: 
```
FAILED mwoauth/tests/test_functions.py::test_process_request_token - TypeError: startswith first arg must be bytes or a tuple of bytes, not str
FAILED mwoauth/tests/test_functions.py::test_process_request_token_errors - TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

... I'm looking into it.

**Comment by halfak** [comment]
It looks like the issue was just that the test was still using bytes rather than a modern string.  I have a minor fix incoming and then we can merge and update the version.

**Comment by halfak** [comment]
OK 0.4.0 limited to py3 is deployed to PyPI

**Comment by a-detiste** [comment]
thanks a lot

**Comment by halfak** [comment]
Thank you!  Dropping python 2 has been a long time coming.

**Pull request merged**
